# Generated by Django 5.0.4 on 2024-05-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelmetDetection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_url',
        ),
        migrations.AddField(
            model_name='image',
            name='image_name',
            field=models.CharField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
