# Generated by Django 5.0.4 on 2024-05-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelmetDetection', '0002_remove_image_image_url_image_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_name',
            field=models.CharField(max_length=30),
        ),
    ]
